### ISSUE TITLE
Native Chrome-logic not compatible / buggy

### ISSUE THREAD

**Issue by fteuber** [aFarkas/respimage#36]
Hi, I'm using chrome 40.0.2214.115 m on win 7.
Chrome has its own picture / img srcset. Respimange checks for window.HTMLPictureElement and does nothing if the method is already implemented. But chrome's behaviour is quite strange. For instance, when using an src="data:image/gif:..." - attribute, this will often be used instead of the srcset-images. Then there will be no visible Image for some sizes. Respimage seems to work very reliable in those circumstances.

It would be cool to have an option to disable the native browser handling (without this workaround), at least untill the browser implementations are reliable and/or the polyfills are compatible with native implementations.

**Comment by aFarkas** [comment]
Yes, this is a regression bug in Chrome, which is fixed in version 40 (and was introduced with version 40). The only way to fix it is to remove the ``src`` attribute. From my knowledge this also can only happen, if all candidates are lower than 1x.

I'm not sure whether I want to provide a specific fix inside of respimage. In case you are using lazySizes, this bug is automatically fixed for you. 

In case you can't or don't want to include lazySizes, would it be a big problem to do this your own???

JS code for this could look something like this:

```js
if(window.HTMLPictureElement && navigator.userAgent.match(/hrome\/(\d+)/) && (RegExp.$1 == 40)){
    $('img[src^="data:"').removeAttr('src');
}
```

Of course you can also remove the ``src`` attribute entirely from your markup.

**Comment by fteuber** [comment]
Thanks for the insight into this problem. We currently work around this problem using
`window.HTMLPictureElement = null;`
but I'll switch to your code snippet, sounds more reasonable to only fix the one broken browser version ;)

**Comment by aFarkas** [comment]
I just wanted to let you know, that Chrome and Opera updated thier engines, so you won't need the workaround anymore.
