### ISSUE TITLE
Confusion re: empty src, LQIP

### ISSUE THREAD

**Issue by davidhund** [aFarkas/respimage#37]
Hello Alexander,

I am a bit confused re: the best approach for the `src` attr. I noticed respimage advises to use a 'LQIP' while PictureFill advises to leave the `src` empty.

Can you clarify the following?

- Because of the browser Preloader we have double downloads in unsupporting browsers, running respimage.js. Correct?
- ..it handles this intelligently using LQIP. But requires LQ images to be prepared?
- What defines a LQ image? It is not, if I understand correctly, simply a 'small.jpg'...
- What good would a data-uri'd 'blank.gif' do besides "valid HTML"?
- What are the 'perf drawbacks' of an empty `src`?

In my situation I can not prepare LQ images (if that means re-compressing etc) so I went with an empty `src`. Now I wonder if I'm doing it wrong.

TIA.

PS: you are not on Twitter, right? FYI: I asked around there too: https://twitter.com/valuedstandards/status/579999578176503808

**Comment by aFarkas** [comment]
In general: respimage is an improved fork of picturefill. Some changes/improvements also account for the fact, that people want to use an initial src. (Due to some bugs, this isn't even possible with picturefill).

So with respimage you can choose yourself and I actually don't want to dictate/recommend a special markup here. 

Each developer should decide himself which markup he should use. This means you can simply omit the ``src`` attribute or use it. 

So if you use an initial src:

Disadvantage:
- you will have double downloads in Safari and aborted downloads in IE (in IE it depends on how many images you have on the page)

Advantage:
- The LQIP source can serve as an extreme fast impression

In general I saw examples, where LQIP did massively improve the speedindex (fast impression) and examples where no source would have been better. This is something you need to test yourself.

About the other questions:
- A blank image is only for validity.
- Ideally a LQIP image is an image that has a computed resolution of 0.5-0.7 (So a little bit smaller, than a normal small.jpg). In case of a fullwidth image using the small.jpg should be just fine (i.e. it has 640px and on desktop you have width of 1024px- 1280px to prepare for = 0.7 - 0.5). 

Something that becomes more important, if you are not using LQIP, is to add respimage in the documents head. So it can work while the DOM is progressivley parsed.

I hope this helps. It's really not a clear answer. (But compared to picturefill you will have a better perf in any case. (although picturefill is catching up).

**Comment by davidhund** [comment]
Awesome, thanks for the quick reply! 
Much clearer now, that is to say: "it depends" :)
