### ISSUE TITLE
srcset using the wrong image on resize

### ISSUE THREAD

**Issue by cluke009** [aFarkas/respimage#40]
I am trying to load a smaller image first and then a larger one if the window is smaller than 1024px. What happens is when you resize to a larger window very slowly the larger image will stick even though the window is now past the break point set. Am I doing something wrong here or is this a legitimate bug?

https://jsfiddle.net/0sjbr61r/embedded/result/

**Comment by aFarkas** [comment]
Here is a version that works. First thing you have always to answer do you want resolution switching or do you want art direction. In case you want just resolution switching you give the browser the choice to use one candidate. Chrome will not use a lower source, if a higher candidate is already loaded or in cache.

If you want control, which candidates are used, you need to use picture instead of only srcset. Note you can combine srcset with picture. 

Did this help? BTW: Here is a working fiddle of yours: http://jsfiddle.net/0sjbr61r/3/

**Comment by cluke009** [comment]
This makes perfect sense thank you. :thumbsup:
