### ISSUE TITLE
Firefox doesn't switch image on browser resize

### ISSUE THREAD

**Issue by cindreta** [aFarkas/respimage#41]
Firefox version: 38 (both Win and Mac)

I've been having some problem with Firefox where when you resize the browser it actually doesn't load a different image. For an example if you load the browser at 1920px and go down to 1280px which is one of my breakpoints it simply doesn't load that image. When i stay on that resolution and refresh the page it does load the correct version of the image. I don't know why is this happening because in Chrome everything works normal. I don't know if this has something to do with Firefox cache of some sorts or?
If you can let me know if i can hack around it i would be more than happy :))

PS. I event tried some of your original CodePen examples and they don't changes images on resize as well. 

Thx a lot.

**Comment by aFarkas** [comment]
The FF 38 implementation is [still buggy](https://bugzilla.mozilla.org/show_bug.cgi?id=1135812). You should not do anything, because either it will be turned off again or this bug will be fixed before FF38 becomes stable. In case you must still workaround this problem you can try [this script](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/static-gecko-picture/ls.static-gecko-picture.js)

**Comment by cindreta** [comment]
Great, i started to think i was going crazy : ) Anyhow tried your script and it works which is great and it helps me a lot at this moment.  You can close this issue. 

Keep up the great work and you got a beer from me.

Thx a lot.

**Comment by philsbury** [comment]
This issue on Firefox seems to have rolled out in 38.0.1 (drove me mad as all was working nicely before the update!). [Your fix](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/static-gecko-picture/ls.static-gecko-picture.js) sorted it nicely though.
