### ISSUE TITLE
support for currentSrc?

### ISSUE THREAD

**Issue by AMA3** [aFarkas/respimage#42]
Hi Alex, I'm not sure if you're supporting currentSrc or not, but according to this it's pretty important:

https://css-tricks.com/please-update-picturefill/

Apologies if you've already addressed this.

**Comment by aFarkas** [comment]
It's quite important for native supporting browser, it's not important for polyfilled browsers, because you can do this:

```js
var src = img.currentSrc || img.src;
```

In case you want this, you can add it with this plugin:
https://github.com/aFarkas/respimage/tree/gh-pages/plugins/mutation

But this only works in IE9+ not IE8. And well, in native supporting browsers without ``currentSrc`` support, you can't even implement it safely.
