### ISSUE TITLE
respimage still recommended over picturefill?

### ISSUE THREAD

**Issue by DenisMir** [aFarkas/respimage#45]
Is the current version still more bugfree than the picturefill polyfill?

**Comment by aFarkas** [comment]
This depends on your needs and on what pf version you actually think. As you might know. I'm also part of the picturefill core team and worked on improvements for version 2.3.x and now on pf 3.0.

In general with picturefill version 3.0 there is not much need for this project anymore. So my advise would  be either be an early adopter and use [picturefill 3.0 alpha](https://github.com/scottjehl/picturefill/tree/afarkas-pf3-proposal/dist) (We currently have code freeze to come out with a public alpha-2 very soon. And want to have positive or negative feedback) or wait a little bit and still stick with respimage.

In general due to the fact that both scripts are polyfills the migration path is absolutely easy, so you can switch between those projects as you want.

In case you are using the ``picturefill``/``respimage`` API directly, it is also quite easy:

```js
//alias picturefill to respimage and vice versa
if(window.respimage && !window-picturefill){
    window.picturefill = window.respimage;
} else if(window.picturefill && !window.respimage){
    window.respimage = window.picturefill;
}
```

Of course you can do also something like this, what is done in lazySizes:

```js
(window.respimage || window.picturefill)();
```

**Comment by DenisMir** [comment]
@aFarkas Thank you very much. This helps me a lot in the decision process.
